# Generated by Django 4.1.7 on 2023-03-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp on create')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp on update')),
                ('deleted', models.BooleanField(help_text='flag for delete')),
                ('slug', models.TextField(help_text='Article ID for URL', max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp on create')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp on update')),
                ('title', models.TextField(db_index=True, help_text='Title', max_length=100)),
                ('body', models.TextField(help_text='Article body')),
                ('deleted', models.BooleanField(help_text='Flag for delete')),
                ('head', models.BooleanField(db_index=True, default=False, help_text='is used as article content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
