# Generated by Django 4.1.7 on 2023-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp on create')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp on update')),
                ('deleted', models.BooleanField(default=False, help_text='flag for delete')),
                ('title', models.TextField(db_index=True, help_text='Title', max_length=100)),
                ('body', models.TextField(help_text='Article body')),
                ('slug', models.TextField(db_index=True, help_text='Article ID for URL', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
