# Generated by Django 4.1.7 on 2023-03-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_article_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False, help_text='flag for delete'),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='deleted',
            field=models.BooleanField(db_index=True, help_text='Flag for delete'),
        ),
    ]
