# Generated by Django 4.1.7 on 2023-03-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_article_deleted_alter_articlerevision_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerevision',
            name='head',
        ),
        migrations.AddField(
            model_name='article',
            name='head_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_as_head', to='wiki.articlerevision'),
        ),
    ]
